FROM mcr.microsoft.com/devcontainers/dotnet:1-8.0-bookworm

# Update the package manager
RUN apt-get update -y

# Set the working directory
WORKDIR /workspaces

# Upgrade dotnet TODO
# RUN pip install --no-cache-dir --upgrade pip

# Default command for debugging
CMD ["/usr/bin/zsh"]
