FROM mcr.microsoft.com/devcontainers/dotnet:1-8.0-bookworm

# Update the package manager
RUN apt-get update -y

# Set the working directory
WORKDIR /workspaces

# Default command for debugging
CMD ["/usr/bin/zsh"]
